정리/0323/django_07/class/01_auth_template/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

정리/0323/django_07/class/01_auth_template/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

정리/0323/django_07/class/01_auth_template/articles/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    image = models.ImageField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("articles:detail", kwargs={"pk": self.pk})
    


    def __str__(self):
        return f'{self.id}번째글 - {self.title}'

정리/0323/django_07/class/01_auth_template/articles/forms.py
from django import forms
from .models import Article

# class ArticleForm(forms.Form):
#     title = forms.CharField(max_length=30)
#     content = forms.CharField(widget=forms.Textarea)

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = '__all__'

정리/0323/django_07/class/01_auth_template/articles/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Article
from .forms import ArticleForm
from django.views.decorators.http import require_http_methods

# Create your views here.
@require_http_methods(['GET'])
def index(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'articles/index.html', context)


def detail(request, pk):    
    article = Article.objects.get(pk=pk)
    context = {'article': article}
    return render(request, 'articles/detail.html', context)

@require_http_methods(['GET','POST'])
def create(request):
    if not request.user.is_authenticated:
        # reverse: 전달받은 Name에 매칭된 url을 문자열로 반환
        # print(reverse('accounts:login'))
        return redirect(reverse('accounts:login') + f'?next={request.path}')
        # return redirect(f'/accounts/login?next={request.path}')
        # return redirect('accounts:login')
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    next = request.GET.get('next')
    context = {
        'form': form,
        'next': next
        }
    return render(request, 'articles/create.html', context)

@require_http_methods(['POST'])
def delete(request, pk):
    if not request.user.is_authenticated:
        return redirect(reverse('accounts:login')+f'?next=/articles/{pk}')
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index')

@require_http_methods(['GET','POST'])
def update(request, pk):
    article = Article.objects.get(pk=pk)

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', pk=article.pk)
    else:
        form = ArticleForm(instance=article)

    context = {'form': form, 'article': article}
    return render(request, 'articles/update.html', context)

정리/0323/django_07/class/01_auth_template/articles/templates/articles/create.html
{% extends 'base.html' %} 

{% block content %}
  <h1>글작성</h1>
  <hr />
  <form
    action="{% url 'articles:create' %}"
    method="POST"
    enctype="multipart/form-data">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="작성하기"/>
  </form>
  <br />
  <hr>
  <a href="{% url 'articles:index' %}">목록보기</a>
{% endblock content %}

정리/0323/django_07/class/01_auth_template/articles/templates/articles/detail.html
{% extends 'base.html' %} 

{% block content %}
  <h1>DETAIL</h1>
  <hr />

  {% if article.image %}
    <img src="{{article.image.url}}" />
  {% endif %}

  <div id="article-content">
    <p>글 제목 : {{article.title}}</p>
    <p>글 내용 : {{article.content}}</p>
    <p>생성시각 : {{article.created_at}}</p>
    <p>수정시각 : {{article.updated_at}}</p>

    <hr>
    <a href="{% url 'articles:update' article.pk %}">수정하기</a>
    <form action="{% url 'articles:delete' article.pk %}" id="delete-form" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제하기" id="delete-btn" />
    </form><br>
    <hr>
    <a href="{% url 'articles:index' %}">목록보기</a>
  </div>
{% endblock content %}

정리/0323/django_07/class/01_auth_template/articles/templates/articles/index.html
{% extends 'base.html' %} 

{% block content %}
  <h1>INDEX</h1>
  <a href="{% url 'articles:create' %}">작성하기</a>
  <hr />

  {% for article in articles %}
    <p>
      {% comment %} [{{article.id}}] <a href="{% url 'articles:detail' article.pk %}" id="article-title">{{article.title}}</a> {% endcomment %}
      [{{article.id}}] <a href="{{ article.get_absolute_url}}" id="article-title">{{article.title}}</a>

    </p>
    <hr />
  {% endfor %} 

{% endblock content %}

정리/0323/django_07/class/01_auth_template/articles/templates/articles/update.html
{% extends 'base.html' %} 

{% block content %}
  <h1>글수정</h1>
  <hr />

  <form action="{% url 'articles:update' article.pk %}" method="POST"  enctype='multipart/form-data'>
    {% csrf_token %} {{form.as_p}}
    <input type="submit" />
  </form>

  <hr />
  <a href="{% url 'articles:detail' article.pk %}">돌아가기</a>
{% endblock content %}